version: '3'
services:
  flask:
    image: autocem-docker-local.artifactory-v.prod.rmn.local/flask:1.0
    container_name: flask
    ports:
      - 5000:5000
    volumes:
      - ./app:/app
    restart: always
    command: python -u main.py
